<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CRM"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="6.763">
  <properties />
            <testcase name="logInToCRM" time="3.909" classname="com.hs18.Test.CRM.LogInTest">
                <failure type="java.lang.AssertionError"
                  message="expected [Invalid credential] but found [Invalid credentials]"
              >
<![CDATA[java.lang.AssertionError: expected [Invalid credential] but found [Invalid credentials]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:496)
  org.testng.Assert.assertEquals(Assert.java:125)
  org.testng.Assert.assertEquals(Assert.java:178)
  org.testng.Assert.assertEquals(Assert.java:188)
  com.hs18.Test.CRM.LogInTest.logInToCRM(LogInTest.java)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:606)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:773)
  org.testng.TestRunner.run(TestRunner.java:623)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
  org.testng.TestNG.run(TestNG.java:1018)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="logInToCRM" time="2.854" classname="com.hs18.Test.CRM.LogInTest" />
      
</testsuite>
